# bag_grid_list = ['item_btn1', 'item_btn2', 'item_btn3', 'item_btn4', 'item_btn5', 'item_btn6', 'item_btn7', 'item_btn8',
#                  'item_btn9', 'item_btn10', 'item_btn11', 'item_btn12', 'item_btn13', 'item_btn14', 'item_btn15',
#                  'item_btn16', 'item_btn17', 'item_btn18', 'item_btn19', 'item_btn20', 'item_btn21', 'item_btn22',
#                  'item_btn23', 'item_btn24', 'item_btn25', 'item_btn26', 'item_btn27', 'item_btn28', 'item_btn29',
#                  'item_btn30', 'item_btn31', 'item_btn32', 'item_btn33', 'item_btn34', 'item_btn35', 'item_btn36']
#
# bag_info = {'/main_panel/inv_grid/item_btn31': {'slot': 30, 'item': {'itemId': 58, 'count': 64, 'modItemId': '',
#                                                                      'enchantData': [], 'durability': 0,
#                                                                      'customTips': '', 'extraId': '', 'modId': '',
#                                                                      'userData': None, 'isDiggerItem': False,
#                                                                      'itemName': 'minecraft:crafting_table',
#                                                                      'auxValue': 0, 'showInHand': True}},
#             '/main_panel/inv_grid/item_btn30': {'slot': 29, 'item': None},
#             '/main_panel/inv_grid/item_btn11': {'slot': 10, 'item': None},
#             '/main_panel/inv_grid/item_btn10': {'slot': 9, 'item': None},
#             '/main_panel/inv_grid/item_btn13': {'slot': 12, 'item': {'itemId': -749, 'count': 64, 'modItemId': '',
#                                                                      'enchantData': [], 'durability': 0,
#                                                                      'customTips': '', 'extraId': '', 'modId': '',
#                                                                      'userData': None, 'isDiggerItem': False,
#                                                                      'itemName': 'xl:infinite_ender_chest',
#                                                                      'auxValue': 0, 'showInHand': True}},
#             '/main_panel/inv_grid/item_btn12': {'slot': 11, 'item': {'itemId': -747, 'count': 64, 'modItemId': '',
#                                                                      'enchantData': [], 'durability': 0,
#                                                                      'customTips': '', 'extraId': '', 'modId': '',
#                                                                      'userData': None, 'isDiggerItem': False,
#                                                                      'itemName': 'xl_iet:infinity_enchant_table',
#                                                                      'auxValue': 0, 'showInHand': True}},
#             '/main_panel/inv_grid/item_btn15': {'slot': 14, 'item': {'itemId': -746, 'count': 52, 'modItemId': '',
#                                                                      'enchantData': [], 'durability': 0,
#                                                                      'customTips': '', 'extraId': '', 'modId': '',
#                                                                      'userData': None, 'isDiggerItem': False,
#                                                                      'itemName': 'xl:block_compress_table',
#                                                                      'auxValue': 0, 'showInHand': True}},
#             '/main_panel/inv_grid/item_btn14': {'slot': 13, 'item': None},
#             '/main_panel/inv_grid/item_btn17': {'slot': 16, 'item': None},
#             '/main_panel/inv_grid/item_btn16': {'slot': 15, 'item': None},
#             '/main_panel/inv_grid/item_btn19': {'slot': 18, 'item': None},
#             '/main_panel/inv_grid/item_btn18': {'slot': 17, 'item': None},
#             '/main_panel/inv_grid/item_btn34': {'slot': 33, 'item': None},
#             '/main_panel/inv_grid/item_btn24': {'slot': 23, 'item': None},
#             '/main_panel/inv_grid/item_btn25': {'slot': 24, 'item': None},
#             '/main_panel/inv_grid/item_btn26': {'slot': 25, 'item': None}，
#
# slot_to_path = {0: '/main_panel/inv_grid/item_btn1', 1: '/main_panel/inv_grid/item_btn2',
#                 2: '/main_panel/inv_grid/item_btn3', 3: '/main_panel/inv_grid/item_btn4',
#                 4: '/main_panel/inv_grid/item_btn5', 5: '/main_panel/inv_grid/item_btn6',
#                 6: '/main_panel/inv_grid/item_btn7', 7: '/main_panel/inv_grid/item_btn8',
#                 8: '/main_panel/inv_grid/item_btn9', 9: '/main_panel/inv_grid/item_btn10',
#                 10: '/main_panel/inv_grid/item_btn11', 11: '/main_panel/inv_grid/item_btn12',
#                 12: '/main_panel/inv_grid/item_btn13', 13: '/main_panel/inv_grid/item_btn14',
#                 14: '/main_panel/inv_grid/item_btn15', 15: '/main_panel/inv_grid/item_btn16',
#                 16: '/main_panel/inv_grid/item_btn17', 17: '/main_panel/inv_grid/item_btn18',
#                 18: '/main_panel/inv_grid/item_btn19', 19: '/main_panel/inv_grid/item_btn20',
#                 20: '/main_panel/inv_grid/item_btn21', 21: '/main_panel/inv_grid/item_btn22',
#                 22: '/main_panel/inv_grid/item_btn23', 23: '/main_panel/inv_grid/item_btn24',
#                 24: '/main_panel/inv_grid/item_btn25', 25: '/main_panel/inv_grid/item_btn26',
#                 26: '/main_panel/inv_grid/item_btn27', 27: '/main_panel/inv_grid/item_btn28',
#                 28: '/main_panel/inv_grid/item_btn29', 29: '/main_panel/inv_grid/item_btn30',
#                 30: '/main_panel/inv_grid/item_btn31', 31: '/main_panel/inv_grid/item_btn32',
#                 32: '/main_panel/inv_grid/item_btn33', 33: '/main_panel/inv_grid/item_btn34',
#                 34: '/main_panel/inv_grid/item_btn35', 35: '/main_panel/inv_grid/item_btn36'}

# args = {'from_slot': 15, 'block_name': 'xl:block_compress_table',
#         'from_item': {'itemId': -746, 'count': 64, 'isDiggerItem': False, 'enchantData': [], 'durability': 0,
#                       'customTips': '', 'extraId': '', 'modId': '', 'userData': None, 'modItemId': '',
#                       'itemName': 'xl:block_compress_table', 'auxValue': 0, 'showInHand': True},
#         'to_item': {'itemId': -745, 'count': 64, 'isDiggerItem': False, 'enchantData': [], 'durability': 0,
#                     'customTips': '', 'extraId': '', 'modId': '', 'userData': None, 'modItemId': '',
#                     'itemName': 'xl:block_limited_compress_table', 'auxValue': 0, 'showInHand': True},
#         'to_slot': 16, 'player_id': '-38654705663', 'block_pos': (3046, 68, 16), 'take_percent': 1, 'dimension': 0}
#
# args = {'from_slot': 12, 'block_name': 'xl:block_compress_table',
#         'from_item': {'itemId': -746, 'count': 64, 'isDiggerItem': False, 'enchantData': [], 'durability': 0,
#                       'customTips': '', 'extraId': '', 'modId': '', 'userData': None, 'modItemId': '',
#                       'itemName': 'xl:block_compress_table', 'auxValue': 0, 'showInHand': True},
#         'to_item': {'itemId': 58, 'count': 64, 'isDiggerItem': False, 'enchantData': [], 'durability': 0,
#                     'customTips': '', 'extraId': '', 'modId': '', 'userData': None, 'modItemId': '',
#                     'itemName': 'minecraft:crafting_table', 'auxValue': 0, 'showInHand': True},
#         'to_slot': 3, 'player_id': '-38654705663', 'block_pos': (3046, 68, 16), 'take_percent': 1, 'dimension': 0}
